name: Rust

on:
  push:
    branches: [ "main", "dev"]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Rust nightly
      run: rustup default nightly
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run fix
      run: cargo fix --allow-staged --allow-dirty
